< Python-Error-解決-Log🔥 >

[ 2022/09/22 エラー解決済み🔥 ]

1. Pythonを実行したら AttributeError がでるエラーの解決法

[ Src-Code ]

    ファイル名: http.py

    import requests
    import pprint

    response = requests.get("https://jsonplaceholder.typicode.com/users")

    pprint.pprint(response)


[ Error-MSG ]

    AttributeError: partially initialized module 'requests' has no attribute 'get' (most likely due to a circular import)

[ 翻訳 ]

    AttributeError: 部分的に初期化されたモジュール 'requests' に属性 'get' がありません (循環インポートが原因である可能性が最も高い)

[ 原因 ]

    ファイル名がエラーの原因です。

    自分自身を モジュールとして import して循環してしまったことです。

    自分自身を循環参照してしまっているから🔥

    本来のrequestsモジュールをインポート出来ずに、ローカルのファイルをインポートしてしまっている。

[ 解決方法 ]

    ファイル名を変えれば、解決🔥
